# ENGR481 Project Stage 1

By: Jared Paull, Liam Ross

The first step that must be taken is to import the necessary libraries for the project

In [90]:
# Trim un-needed libraries later

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits import mplot3d
from autograd import grad
from autograd import hessian
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn import linear_model
import os
from sklearn.metrics import confusion_matrix

import PIL

In [59]:
# Great resource: https://www.pluralsight.com/guides/importing-image-data-into-numpy-arrays

# import image using Pillow library
image = PIL.Image.open("../data/training/cir_1.png").convert("L")

image = PIL.Image.fromarray(np.array(image)[int(np.floor(image.height / 4)) : int(np.ceil(3 * image.height / 4)), int(np.floor(image.width / 4)) : int(np.ceil( 3 * image.width / 4))])

image = image.resize((64,64))

#image.show()


# print(image.format)
# print(image.size)
# print(image.mode)


# stores data in 3D array, first dimension is row, second dim is col, third dim is [R G B] value for the pixel.
data = np.asarray(image)

print(type(data))

# summarize shape
#print(data.shape)
#print(data)
vec = np.hstack(data)
print(vec)


<class 'numpy.ndarray'>
[131 131 132 ... 159 159 160]


In [82]:
x = []
y = []
for pic in os.listdir("../data/training/"):
    image = PIL.Image.open(f"../data/training/{pic}").convert("L")
    image = PIL.Image.fromarray(np.array(image)[int(np.floor(image.height / 4)) : int(np.ceil(3 * image.height / 4)), int(np.floor(image.width / 4)) : int(np.ceil( 3 * image.width / 4))])
    image = image.resize((64,64))
    data = np.asarray(image)
    vec = np.hstack(data)
    x.append(vec)
    
    if( str.lower(pic[0]) == "c"):
        y.append(0)
    elif (str.lower(pic[0]) == "r"):
        y.append(1)
    else:
        y.append(2)
    
x = np.array(x)
y = np.array(y)

print(x,"\n", y)


[[131 131 132 ... 159 159 160]
 [208 207 208 ... 199 199 200]
 [206 206 206 ... 196 195 196]
 ...
 [143 143 142 ... 197 196 196]
 [180 181 181 ... 206 206 205]
 [196 196 195 ... 220 220 222]] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [79]:
log_regress = linear_model.LogisticRegression(solver = "liblinear")
log_regress.fit(x,y)



LogisticRegression(solver='liblinear')

## Testing the algorithm

In [87]:
xt = []
yt = []
for pic in os.listdir("../data/testing/"):
    image = PIL.Image.open(f"../data/testing/{pic}").convert("L")
    image = PIL.Image.fromarray(np.array(image)[int(np.floor(image.height / 4)) : int(np.ceil(3 * image.height / 4)), int(np.floor(image.width / 4)) : int(np.ceil( 3 * image.width / 4))])
    image = image.resize((64,64))
    data = np.asarray(image)
    vec = np.hstack(data)
    xt.append(vec)
    
    if( str.lower(pic[0]) == "c"):
        yt.append(0)
    elif (str.lower(pic[0]) == "r"):
        yt.append(1)
    else:
        yt.append(2)
    
xt = np.array(xt)
yt = np.array(yt)

print(xt, "\n", yt)

[[196 195 196 ... 190 191 190]
 [124 126 127 ... 150 150 151]
 [166 166 165 ... 180 180 180]
 ...
 [170 169 168 ... 158 158 159]
 [166 165 165 ... 155 156 155]
 [162 161 161 ... 158 157 158]] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [92]:
pred =  log_regress.predict(xt)

cm = confusion_matrix(yt, pred)
print(cm)

[[17  0  1]
 [ 0 17  1]
 [ 1  0 17]]
